[package]
name = "vplot"
version = "0.3.424"
authors = ["Spencer Nystrom <nystromdev@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.3"
bio = "0.40.0"
rust-htslib = {version = "0.32", default-features = false}
structopt = "0.3.18"
ndarray = "0.13.1"
ndarray-csv = "0.4.1"
plotly = "0.6.0"
